version: "3.9"
services:
  mysql:
    image: mysql:latest
    container_name: mydockerdb
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: ecommerce

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

     postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ecommerceUsuarios
    ports:
      
    - "5432:5432" 
